/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param importRequestId 
 * @param status 
 */


data class CreateImportResDto (

    @Json(name = "importRequestId")
    val importRequestId: kotlin.String,

    @Json(name = "status")
    val status: CreateImportResDto.Status

) {

    /**
     * 
     *
     * Values: start,inProgress,done,cancel,error
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "Start") start("Start"),
        @Json(name = "InProgress") inProgress("InProgress"),
        @Json(name = "Done") done("Done"),
        @Json(name = "Cancel") cancel("Cancel"),
        @Json(name = "Error") error("Error");
    }
}

