/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param maps 
 * @param components 
 */


data class DeviceContentResDto (

    @Json(name = "maps")
    val maps: kotlin.collections.List<MapDto>,

    @Json(name = "components")
    val components: kotlin.collections.List<ComponentDto>

)

