/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId 
 * @param productName 
 * @param productVersion 
 * @param productType 
 * @param boundingBox 
 * @param description 
 * @param updateDateUTC 
 */


data class DiscoveryMapResDto (

    @Json(name = "productId")
    val productId: kotlin.String? = null,

    @Json(name = "productName")
    val productName: kotlin.String? = null,

    @Json(name = "productVersion")
    val productVersion: kotlin.String? = null,

    @Json(name = "productType")
    val productType: kotlin.String? = null,

    @Json(name = "boundingBox")
    val boundingBox: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "updateDateUTC")
    val updateDateUTC: java.time.OffsetDateTime? = null

)

