/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param zoomLevel 
 * @param catalogId 
 * @param productId 
 * @param productName 
 * @param fileName 
 * @param createDate 
 * @param boundingBox 
 * @param status 
 * @param packageUrl 
 */


data class MapDto (

    @Json(name = "zoomLevel")
    val zoomLevel: java.math.BigDecimal,

    @Json(name = "catalogId")
    val catalogId: kotlin.String? = null,

    @Json(name = "productId")
    val productId: kotlin.String? = null,

    @Json(name = "productName")
    val productName: kotlin.String? = null,

    @Json(name = "fileName")
    val fileName: kotlin.String? = null,

    @Json(name = "createDate")
    val createDate: java.time.OffsetDateTime? = null,

    @Json(name = "boundingBox")
    val boundingBox: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "packageUrl")
    val packageUrl: kotlin.String? = null

)

