/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param member 
 * @param projects 
 */


data class MemberProjectsResDto (

    @Json(name = "member")
    val member: MemberResDto? = null,

    @Json(name = "projects")
    val projects: kotlin.collections.List<ProjectResDto>? = null

)

