/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param isNewVersion 
 * @param platform 
 */


data class OfferingResponseDto (

    @Json(name = "isNewVersion")
    val isNewVersion: kotlin.Boolean? = null,

    @Json(name = "platform")
    val platform: PlatformDto? = null

)

