/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param weather 
 * @param bandwidth 
 * @param time 
 * @param operativeState 
 * @param power 
 * @param location 
 */


data class SituationalDiscoveryDto (

    @Json(name = "weather")
    val weather: java.math.BigDecimal? = null,

    @Json(name = "bandwidth")
    val bandwidth: java.math.BigDecimal? = null,

    @Json(name = "time")
    val time: java.time.OffsetDateTime? = null,

    @Json(name = "operativeState")
    val operativeState: kotlin.Boolean? = null,

    @Json(name = "power")
    val power: java.math.BigDecimal? = null,

    @Json(name = "location")
    val location: GeoLocationDto? = null

)

