/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status 
 * @param catalogId 
 * @param uploadToken 
 */


data class UpdateUploadStatusDto (

    @Json(name = "status")
    val status: UpdateUploadStatusDto.Status,

    @Json(name = "catalogId")
    val catalogId: kotlin.String? = null,

    @Json(name = "uploadToken")
    val uploadToken: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: started,downloadingMinusFromMinusUrl,failMinusToMinusDownload,uploadingMinusToMinusS3,failMinusToMinusUpload,inMinusProgress,ready,error
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "started") started("started"),
        @Json(name = "downloading-from-url") downloadingMinusFromMinusUrl("downloading-from-url"),
        @Json(name = "fail-to-download") failMinusToMinusDownload("fail-to-download"),
        @Json(name = "uploading-to-s3") uploadingMinusToMinusS3("uploading-to-s3"),
        @Json(name = "fail-to-upload") failMinusToMinusUpload("fail-to-upload"),
        @Json(name = "in-progress") inMinusProgress("in-progress"),
        @Json(name = "ready") ready("ready"),
        @Json(name = "error") error("error");
    }
}

