/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maxCapacityInGB 
 * @param mes 
 */


data class CacheConfigDto (

    @Json(name = "maxCapacityInGB")
    val maxCapacityInGB: java.math.BigDecimal,

    @Json(name = "mes")
    val mes: kotlin.String

)

