/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param catalogId 
 * @param name 
 * @param versionNumber 
 * @param releaseNotes 
 * @param virtualSize 
 * @param category 
 * @param baseVersion 
 * @param prevVersion 
 * @param latest 
 * @param uploadDate 
 * @param subComponents 
 */


data class ComponentDto (

    @Json(name = "catalogId")
    val catalogId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "versionNumber")
    val versionNumber: kotlin.String? = null,

    @Json(name = "releaseNotes")
    val releaseNotes: kotlin.String? = null,

    @Json(name = "virtualSize")
    val virtualSize: java.math.BigDecimal? = null,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "baseVersion")
    val baseVersion: kotlin.String? = null,

    @Json(name = "prevVersion")
    val prevVersion: kotlin.String? = null,

    @Json(name = "latest")
    val latest: kotlin.Boolean? = null,

    @Json(name = "uploadDate")
    val uploadDate: java.time.OffsetDateTime? = null,

    @Json(name = "subComponents")
    val subComponents: kotlin.collections.List<ComponentDto>? = null

)

