/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertySize 
 * @param date 
 * @param catalogId 
 */


data class DeleteFromCacheDto (

    @Json(name = "size")
    val propertySize: java.math.BigDecimal? = null,

    @Json(name = "date")
    val date: kotlin.String? = null,

    @Json(name = "catalogId")
    val catalogId: kotlin.Any? = null

)

