/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import GetApp.Client.models.HashDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param catalogId 
 * @param itemKey 
 * @param url 
 * @param metaData 
 * @param propertySize 
 * @param hash 
 */


data class DeliveryItemDto (

    @Json(name = "catalogId")
    val catalogId: kotlin.String,

    @Json(name = "itemKey")
    val itemKey: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "metaData")
    val metaData: kotlin.String? = null,

    @Json(name = "size")
    val propertySize: java.math.BigDecimal? = null,

    @Json(name = "hash")
    val hash: HashDto? = null

)

