/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deviceId 
 * @param catalogId 
 * @param currentTime 
 * @param deployStatus 
 * @param type 
 * @param deployStop 
 * @param deployStart 
 * @param deployDone 
 * @param deployEstimateTime 
 */


data class DeployStatusDto (

    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    @Json(name = "catalogId")
    val catalogId: kotlin.String,

    @Json(name = "currentTime")
    val currentTime: java.time.OffsetDateTime,

    @Json(name = "deployStatus")
    val deployStatus: DeployStatusDto.DeployStatus,

    @Json(name = "type")
    val type: DeployStatusDto.Type,

    @Json(name = "deployStop")
    val deployStop: java.time.OffsetDateTime? = null,

    @Json(name = "deployStart")
    val deployStart: java.time.OffsetDateTime? = null,

    @Json(name = "deployDone")
    val deployDone: java.time.OffsetDateTime? = null,

    @Json(name = "deployEstimateTime")
    val deployEstimateTime: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: Start,Done,Installing,Continue,Pause,Cancelled,Error,Uninstall
     */
    @JsonClass(generateAdapter = false)
    enum class DeployStatus(val value: kotlin.String) {
        @Json(name = "Start") Start("Start"),
        @Json(name = "Done") Done("Done"),
        @Json(name = "Installing") Installing("Installing"),
        @Json(name = "Continue") Continue("Continue"),
        @Json(name = "Pause") Pause("Pause"),
        @Json(name = "Cancelled") Cancelled("Cancelled"),
        @Json(name = "Error") Error("Error"),
        @Json(name = "Uninstall") Uninstall("Uninstall");
    }
    /**
     * 
     *
     * Values: software,map,cache
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "software") software("software"),
        @Json(name = "map") map("map"),
        @Json(name = "cache") cache("cache");
    }
}

