/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import GetApp.Client.models.DeviceMapDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param devices 
 * @param groups 
 */


data class DevicesGroupDto (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "devices")
    val devices: kotlin.collections.List<DeviceMapDto>? = null,

    @Json(name = "groups")
    val groups: kotlin.collections.List<DevicesGroupDto>? = null

)

