/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param zadikNumber 
 * @param hardware 
 * @param formation 
 * @param availableStorage 
 * @param power 
 * @param bandwidth 
 */


data class DeviceMapDto (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "zadikNumber")
    val zadikNumber: kotlin.String? = null,

    @Json(name = "hardware")
    val hardware: kotlin.String? = null,

    @Json(name = "formation")
    val formation: kotlin.String? = null,

    @Json(name = "availableStorage")
    val availableStorage: kotlin.String? = null,

    @Json(name = "power")
    val power: java.math.BigDecimal? = null,

    @Json(name = "bandwidth")
    val bandwidth: java.math.BigDecimal? = null

)

