/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param orgUID Set the unique given id or null to remove the exists uid.
 */


data class DevicePutDto (

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Set the unique given id or null to remove the exists uid. */
    @Json(name = "orgUID")
    val orgUID: java.math.BigDecimal? = null

)

