/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count 
 * @param updated 
 * @param onUpdateProcess 
 * @param updateError 
 */


data class DevicesStatisticInfo (

    @Json(name = "count")
    val count: java.math.BigDecimal,

    @Json(name = "updated")
    val updated: java.math.BigDecimal,

    @Json(name = "onUpdateProcess")
    val onUpdateProcess: java.math.BigDecimal,

    @Json(name = "updateError")
    val updateError: java.math.BigDecimal

)

