/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import GetApp.Client.models.ComponentDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param offer 
 * @param push 
 */


data class DeviceComponentsOfferingDto (

    @Json(name = "offer")
    val offer: kotlin.collections.List<ComponentDto>,

    @Json(name = "push")
    val push: kotlin.collections.List<ComponentDto>

)

