/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId 
 * @param productName 
 * @param productVersion 
 * @param productType 
 * @param description 
 * @param boundingBox 
 * @param crs 
 * @param imagingTimeStart 
 * @param imagingTimeEnd 
 * @param creationDate 
 * @param source 
 * @param classification 
 * @param compartmentalization 
 * @param region 
 * @param sensor 
 * @param precisionLevel 
 * @param resolution 
 * @param inventory 
 */


data class DiscoveryMapDto (

    @Json(name = "productId")
    val productId: kotlin.String? = null,

    @Json(name = "productName")
    val productName: kotlin.String? = null,

    @Json(name = "productVersion")
    val productVersion: kotlin.String? = null,

    @Json(name = "productType")
    val productType: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "boundingBox")
    val boundingBox: kotlin.String? = null,

    @Json(name = "crs")
    val crs: kotlin.String? = null,

    @Json(name = "imagingTimeStart")
    val imagingTimeStart: kotlin.String? = null,

    @Json(name = "imagingTimeEnd")
    val imagingTimeEnd: kotlin.String? = null,

    @Json(name = "creationDate")
    val creationDate: kotlin.String? = null,

    @Json(name = "source")
    val source: kotlin.String? = null,

    @Json(name = "classification")
    val classification: kotlin.String? = null,

    @Json(name = "compartmentalization")
    val compartmentalization: kotlin.String? = null,

    @Json(name = "region")
    val region: kotlin.String? = null,

    @Json(name = "sensor")
    val sensor: kotlin.String? = null,

    @Json(name = "precisionLevel")
    val precisionLevel: kotlin.String? = null,

    @Json(name = "resolution")
    val resolution: kotlin.String? = null,

    @Json(name = "inventory")
    val inventory: kotlin.collections.List<kotlin.String>? = null

)

