/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param formation 
 * @param platform 
 */


data class DiscoverySoftwareDto (

    @Json(name = "formation")
    val formation: kotlin.String? = null,

    @Json(name = "platform")
    val platform: PlatformDto? = null

)

