/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param errorCode `MAP.unknown`: Error code not listed in the enum <br /> `MAP.notFound`: No found the map with given id <br /> `MAP.bBoxIsInvalid`: BBox is probably invalid <br /> `MAP.bBoxNotInAnyPolygon`: The given BBox in not contains in any polygon <br /> `MAP.exportMapFailed`: Some error occurs when import map <br /> `MAP.requestInProgress`: Delivery was already requested and in processing! <br /> `MAP.areaTooLarge`: Area too large to distribute, reduce request size and try again <br /> `MAP.areaTooSmall`: Area too small to distribute, increase request size and try again . 
 * @param message 
 */


data class ErrorDto (

    /* `MAP.unknown`: Error code not listed in the enum <br /> `MAP.notFound`: No found the map with given id <br /> `MAP.bBoxIsInvalid`: BBox is probably invalid <br /> `MAP.bBoxNotInAnyPolygon`: The given BBox in not contains in any polygon <br /> `MAP.exportMapFailed`: Some error occurs when import map <br /> `MAP.requestInProgress`: Delivery was already requested and in processing! <br /> `MAP.areaTooLarge`: Area too large to distribute, reduce request size and try again <br /> `MAP.areaTooSmall`: Area too small to distribute, increase request size and try again .  */
    @Json(name = "errorCode")
    val errorCode: ErrorDto.ErrorCode? = null,

    @Json(name = "message")
    val message: kotlin.String? = null

) {

    /**
     * `MAP.unknown`: Error code not listed in the enum <br /> `MAP.notFound`: No found the map with given id <br /> `MAP.bBoxIsInvalid`: BBox is probably invalid <br /> `MAP.bBoxNotInAnyPolygon`: The given BBox in not contains in any polygon <br /> `MAP.exportMapFailed`: Some error occurs when import map <br /> `MAP.requestInProgress`: Delivery was already requested and in processing! <br /> `MAP.areaTooLarge`: Area too large to distribute, reduce request size and try again <br /> `MAP.areaTooSmall`: Area too small to distribute, increase request size and try again . 
     *
     * Values: MAPPeriodUnknown,MAPPeriodNotFound,MAPPeriodBBoxIsInvalid,MAPPeriodBBoxNotInAnyPolygon,MAPPeriodExportMapFailed,MAPPeriodRequestInProgress,MAPPeriodAreaTooLarge,MAPPeriodAreaTooSmall
     */
    @JsonClass(generateAdapter = false)
    enum class ErrorCode(val value: kotlin.String) {
        @Json(name = "MAP.unknown") MAPPeriodUnknown("MAP.unknown"),
        @Json(name = "MAP.notFound") MAPPeriodNotFound("MAP.notFound"),
        @Json(name = "MAP.bBoxIsInvalid") MAPPeriodBBoxIsInvalid("MAP.bBoxIsInvalid"),
        @Json(name = "MAP.bBoxNotInAnyPolygon") MAPPeriodBBoxNotInAnyPolygon("MAP.bBoxNotInAnyPolygon"),
        @Json(name = "MAP.exportMapFailed") MAPPeriodExportMapFailed("MAP.exportMapFailed"),
        @Json(name = "MAP.requestInProgress") MAPPeriodRequestInProgress("MAP.requestInProgress"),
        @Json(name = "MAP.areaTooLarge") MAPPeriodAreaTooLarge("MAP.areaTooLarge"),
        @Json(name = "MAP.areaTooSmall") MAPPeriodAreaTooSmall("MAP.areaTooSmall");
    }

}

