/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lat 
 * @param long 
 * @param alt 
 */


data class GeoLocationDto (

    @Json(name = "lat")
    val lat: kotlin.String? = null,

    @Json(name = "long")
    val long: kotlin.String? = null,

    @Json(name = "alt")
    val alt: kotlin.String? = null

) {


}

