/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param algorithm 
 * @param hash 
 */


data class HashDto (

    @Json(name = "algorithm")
    val algorithm: kotlin.Any,

    @Json(name = "hash")
    val hash: kotlin.String

)

