/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import GetApp.Client.models.ErrorDto
import GetApp.Client.models.MapMetadatatDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param importRequestId 
 * @param status 
 * @param error 
 * @param metaData 
 */


data class ImportStatusResDto (

    @Json(name = "importRequestId")
    val importRequestId: kotlin.String? = null,

    @Json(name = "status")
    val status: ImportStatusResDto.Status? = null,

    @Json(name = "error")
    val error: ErrorDto? = null,

    @Json(name = "metaData")
    val metaData: MapMetadatatDto? = null

) {

    /**
     * 
     *
     * Values: start,inProgress,done,cancel,pause,error,pending,expired,archived
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "Start") start("Start"),
        @Json(name = "InProgress") inProgress("InProgress"),
        @Json(name = "Done") done("Done"),
        @Json(name = "Cancel") cancel("Cancel"),
        @Json(name = "Pause") pause("Pause"),
        @Json(name = "Error") error("Error"),
        @Json(name = "Pending") pending("Pending"),
        @Json(name = "Expired") expired("Expired"),
        @Json(name = "Archived") archived("Archived");
    }
}

