/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import GetApp.Client.models.ErrorDto
import GetApp.Client.models.MapMetadatatDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param importRequestId 
 * @param status 
 * @param error 
 * @param metaData 
 */


data class ImportStatusResDto (

    @Json(name = "importRequestId")
    val importRequestId: kotlin.String? = null,

    @Json(name = "status")
    val status: ImportStatusResDto.Status? = null,

    @Json(name = "error")
    val error: ErrorDto? = null,

    @Json(name = "metaData")
    val metaData: MapMetadatatDto? = null

) {

    /**
     * 
     *
     * Values: Start,InProgress,Done,Cancel,Pause,Error,Pending,Expired,Archived
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "Start") Start("Start"),
        @Json(name = "InProgress") InProgress("InProgress"),
        @Json(name = "Done") Done("Done"),
        @Json(name = "Cancel") Cancel("Cancel"),
        @Json(name = "Pause") Pause("Pause"),
        @Json(name = "Error") Error("Error"),
        @Json(name = "Pending") Pending("Pending"),
        @Json(name = "Expired") Expired("Expired"),
        @Json(name = "Archived") Archived("Archived");
    }
}

