/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deviceId 
 * @param inventory 
 */


data class InventoryUpdatesReqDto (

    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    @Json(name = "inventory")
    val inventory: kotlin.collections.List<kotlin.String>

)

