/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deviceId 
 * @param inventory 
 */


data class InventoryUpdatesReqDto (

    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    @Json(name = "inventory")
    val inventory: kotlin.collections.Map<kotlin.String,InventoryUpdatesReqDto.Inventory>

) {

    /**
     * 
     *
     * Values: offering,push,`import`,delivery,installed,uninstalled
     */
    @JsonClass(generateAdapter = false)
    enum class Inventory(val value: kotlin.String) {
        @Json(name = "offering") offering("offering"),
        @Json(name = "push") push("push"),
        @Json(name = "import") `import`("import"),
        @Json(name = "delivery") delivery("delivery"),
        @Json(name = "installed") installed("installed"),
        @Json(name = "uninstalled") uninstalled("uninstalled");
    }
}

