/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deliveryTimeout 
 * @param maxMapSizeInMeter 
 * @param maxParallelDownloads 
 * @param downloadRetryTime 
 * @param downloadTimeoutSec 
 * @param periodicForInventoryJob 
 * @param periodicForMapConf 
 * @param minSpaceByte 
 */


data class MapConfigDto (

    @Json(name = "deliveryTimeout")
    val deliveryTimeout: java.math.BigDecimal? = null,

    @Json(name = "maxMapSizeInMeter")
    val maxMapSizeInMeter: java.math.BigDecimal? = null,

    @Json(name = "maxParallelDownloads")
    val maxParallelDownloads: java.math.BigDecimal? = null,

    @Json(name = "downloadRetryTime")
    val downloadRetryTime: java.math.BigDecimal? = null,

    @Json(name = "downloadTimeoutSec")
    val downloadTimeoutSec: java.math.BigDecimal? = null,

    @Json(name = "periodicForInventoryJob")
    val periodicForInventoryJob: java.math.BigDecimal? = null,

    @Json(name = "periodicForMapConf")
    val periodicForMapConf: java.math.BigDecimal? = null,

    @Json(name = "minSpaceByte")
    val minSpaceByte: java.math.BigDecimal? = null

)

