/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param jobId 
 * @param mapId 
 * @param exportStart 
 * @param exportEnd 
 * @param progress 
 * @param propertySize 
 * @param zoomLevel 
 * @param packageUrl 
 * @param fileName 
 */


data class MapMetadatatDto (

    @Json(name = "jobId")
    val jobId: java.math.BigDecimal? = null,

    @Json(name = "mapId")
    val mapId: kotlin.String? = null,

    @Json(name = "exportStart")
    val exportStart: java.time.OffsetDateTime? = null,

    @Json(name = "exportEnd")
    val exportEnd: java.time.OffsetDateTime? = null,

    @Json(name = "progress")
    val progress: kotlin.Int? = 0,

    @Json(name = "size")
    val propertySize: kotlin.Int? = 0,

    @Json(name = "zoomLevel")
    val zoomLevel: kotlin.Int? = 1,

    @Json(name = "packageUrl")
    val packageUrl: kotlin.String? = null,

    @Json(name = "fileName")
    val fileName: kotlin.String? = null

)

