/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param productId 
 * @param footprint 
 * @param productName 
 * @param productVersion 
 * @param productType 
 * @param productSubType 
 * @param description 
 * @param imagingTimeBeginUTC 
 * @param imagingTimeEndUTC 
 * @param maxResolutionDeg 
 * @param transparency 
 * @param region 
 * @param ingestionDate 
 */


data class MapProductResDto (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "productId")
    val productId: kotlin.String,

    @Json(name = "footprint")
    val footprint: kotlin.String,

    @Json(name = "productName")
    val productName: kotlin.String? = null,

    @Json(name = "productVersion")
    val productVersion: kotlin.String? = null,

    @Json(name = "productType")
    val productType: kotlin.String? = null,

    @Json(name = "productSubType")
    val productSubType: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "imagingTimeBeginUTC")
    val imagingTimeBeginUTC: java.time.OffsetDateTime? = null,

    @Json(name = "imagingTimeEndUTC")
    val imagingTimeEndUTC: java.time.OffsetDateTime? = null,

    @Json(name = "maxResolutionDeg")
    val maxResolutionDeg: java.math.BigDecimal? = null,

    @Json(name = "transparency")
    val transparency: kotlin.String? = null,

    @Json(name = "region")
    val region: kotlin.String? = null,

    @Json(name = "ingestionDate")
    val ingestionDate: java.time.OffsetDateTime? = null

) {


}

