/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models

import GetApp.Client.models.MapDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param map 
 * @param state 
 */


data class MapStateDto (

    @Json(name = "map")
    val map: MapDto? = null,

    @Json(name = "state")
    val state: MapStateDto.State? = null

) {

    /**
     * 
     *
     * Values: `import`,delivery,installed,uninstalled
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "import") `import`("import"),
        @Json(name = "delivery") delivery("delivery"),
        @Json(name = "installed") installed("installed"),
        @Json(name = "uninstalled") uninstalled("uninstalled");
    }
}

