/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param role 
 * @param id 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param defaultProject 
 */


data class MemberResDto (

    @Json(name = "role")
    val role: MemberResDto.Role,

    @Json(name = "id")
    val id: java.math.BigDecimal? = null,

    @Json(name = "firstName")
    val firstName: kotlin.String? = null,

    @Json(name = "lastName")
    val lastName: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "defaultProject")
    val defaultProject: java.math.BigDecimal? = java.math.BigDecimal("-1")

) {

    /**
     * 
     *
     * Values: projectMinusOwner,projectMinusAdmin,projectMinusMember
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "project-owner") projectMinusOwner("project-owner"),
        @Json(name = "project-admin") projectMinusAdmin("project-admin"),
        @Json(name = "project-member") projectMinusMember("project-member");
    }

}

