/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param catalogId 
 * @param deviceId 
 * @param itemType 
 */


data class PrepareDeliveryReqDto (

    @Json(name = "catalogId")
    val catalogId: kotlin.String,

    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    @Json(name = "itemType")
    val itemType: PrepareDeliveryReqDto.ItemType

) {

    /**
     * 
     *
     * Values: software,map,cache
     */
    @JsonClass(generateAdapter = false)
    enum class ItemType(val value: kotlin.String) {
        @Json(name = "software") software("software"),
        @Json(name = "map") map("map"),
        @Json(name = "cache") cache("cache");
    }

}

