/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param uploadStatus 
 * @param catalogId 
 * @param name 
 * @param platform 
 * @param formation 
 * @param version 
 * @param releaseNotes 
 * @param virtualSize 
 * @param category 
 * @param deploymentStatus 
 * @param securityStatus 
 * @param policyStatus 
 */


data class ProjectReleasesDto (

    @Json(name = "uploadStatus")
    val uploadStatus: ProjectReleasesDto.UploadStatus,

    @Json(name = "catalogId")
    val catalogId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "platform")
    val platform: kotlin.String? = null,

    @Json(name = "formation")
    val formation: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null,

    @Json(name = "releaseNotes")
    val releaseNotes: kotlin.String? = null,

    @Json(name = "virtualSize")
    val virtualSize: java.math.BigDecimal? = null,

    @Json(name = "category")
    val category: kotlin.String? = null,

    @Json(name = "deploymentStatus")
    val deploymentStatus: kotlin.String? = null,

    @Json(name = "securityStatus")
    val securityStatus: kotlin.String? = null,

    @Json(name = "policyStatus")
    val policyStatus: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: started,downloadingMinusFromMinusUrl,failMinusToMinusDownload,uploadingMinusToMinusS3,failMinusToMinusUpload,inMinusProgress,ready,error
     */
    @JsonClass(generateAdapter = false)
    enum class UploadStatus(val value: kotlin.String) {
        @Json(name = "started") started("started"),
        @Json(name = "downloading-from-url") downloadingMinusFromMinusUrl("downloading-from-url"),
        @Json(name = "fail-to-download") failMinusToMinusDownload("fail-to-download"),
        @Json(name = "uploading-to-s3") uploadingMinusToMinusS3("uploading-to-s3"),
        @Json(name = "fail-to-upload") failMinusToMinusUpload("fail-to-upload"),
        @Json(name = "in-progress") inMinusProgress("in-progress"),
        @Json(name = "ready") ready("ready"),
        @Json(name = "error") error("error");
    }

}

