/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param catalogId 
 * @param devices 
 * @param itemType 
 * @param groups 
 */


data class PushOfferingDto (

    @Json(name = "catalogId")
    val catalogId: kotlin.String,

    @Json(name = "devices")
    val devices: kotlin.collections.List<kotlin.String>,

    @Json(name = "itemType")
    val itemType: PushOfferingDto.ItemType = ItemType.software,

    @Json(name = "groups")
    val groups: kotlin.collections.List<java.math.BigDecimal>? = null

) {

    /**
     * 
     *
     * Values: software,map,cache
     */
    @JsonClass(generateAdapter = false)
    enum class ItemType(val value: kotlin.String) {
        @Json(name = "software") software("software"),
        @Json(name = "map") map("map"),
        @Json(name = "cache") cache("cache");
    }
}

