/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param devices 
 * @param groups 
 */


data class SetDevicesInGroupDto (

    @Json(name = "id")
    val id: java.math.BigDecimal,

    @Json(name = "devices")
    val devices: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "groups")
    val groups: kotlin.collections.List<kotlin.String>? = null

)

