/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param expireAt 
 * @param refreshExpireAt 
 */


data class TokensDto (

    @Json(name = "accessToken")
    val accessToken: kotlin.String,

    @Json(name = "refreshToken")
    val refreshToken: kotlin.String,

    @Json(name = "expireAt")
    val expireAt: java.time.OffsetDateTime? = null,

    @Json(name = "refreshExpireAt")
    val refreshExpireAt: java.time.OffsetDateTime? = null

) {


}

