/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package GetApp.Client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import GetApp.Client.models.CreateDevicesGroupDto
import GetApp.Client.models.DevicesGroupDto
import GetApp.Client.models.EditDevicesGroupDto
import GetApp.Client.models.SetDevicesInGroupDto

import com.squareup.moshi.Json

import GetApp.Client.infrastructure.ApiClient
import GetApp.Client.infrastructure.ApiResponse
import GetApp.Client.infrastructure.ClientException
import GetApp.Client.infrastructure.ClientError
import GetApp.Client.infrastructure.ServerException
import GetApp.Client.infrastructure.ServerError
import GetApp.Client.infrastructure.MultiValueMap
import GetApp.Client.infrastructure.PartConfig
import GetApp.Client.infrastructure.RequestConfig
import GetApp.Client.infrastructure.RequestMethod
import GetApp.Client.infrastructure.ResponseType
import GetApp.Client.infrastructure.Success
import GetApp.Client.infrastructure.toMultiValue

class DeviceGroupApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * POST /api/group
     * Create Devices Group
     * 
     * @param createDevicesGroupDto 
     * @return DevicesGroupDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun groupControllerCreateGroup(createDevicesGroupDto: CreateDevicesGroupDto) : DevicesGroupDto {
        val localVarResponse = groupControllerCreateGroupWithHttpInfo(createDevicesGroupDto = createDevicesGroupDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DevicesGroupDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/group
     * Create Devices Group
     * 
     * @param createDevicesGroupDto 
     * @return ApiResponse<DevicesGroupDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun groupControllerCreateGroupWithHttpInfo(createDevicesGroupDto: CreateDevicesGroupDto) : ApiResponse<DevicesGroupDto?> {
        val localVariableConfig = groupControllerCreateGroupRequestConfig(createDevicesGroupDto = createDevicesGroupDto)

        return request<CreateDevicesGroupDto, DevicesGroupDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation groupControllerCreateGroup
     *
     * @param createDevicesGroupDto 
     * @return RequestConfig
     */
    fun groupControllerCreateGroupRequestConfig(createDevicesGroupDto: CreateDevicesGroupDto) : RequestConfig<CreateDevicesGroupDto> {
        val localVariableBody = createDevicesGroupDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/group",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /api/group
     * Edit Devices Group
     * 
     * @param editDevicesGroupDto 
     * @return DevicesGroupDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun groupControllerEditGroup(editDevicesGroupDto: EditDevicesGroupDto) : DevicesGroupDto {
        val localVarResponse = groupControllerEditGroupWithHttpInfo(editDevicesGroupDto = editDevicesGroupDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DevicesGroupDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /api/group
     * Edit Devices Group
     * 
     * @param editDevicesGroupDto 
     * @return ApiResponse<DevicesGroupDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun groupControllerEditGroupWithHttpInfo(editDevicesGroupDto: EditDevicesGroupDto) : ApiResponse<DevicesGroupDto?> {
        val localVariableConfig = groupControllerEditGroupRequestConfig(editDevicesGroupDto = editDevicesGroupDto)

        return request<EditDevicesGroupDto, DevicesGroupDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation groupControllerEditGroup
     *
     * @param editDevicesGroupDto 
     * @return RequestConfig
     */
    fun groupControllerEditGroupRequestConfig(editDevicesGroupDto: EditDevicesGroupDto) : RequestConfig<EditDevicesGroupDto> {
        val localVariableBody = editDevicesGroupDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/group",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/group/{groupId}/devices
     * Get Devices in a group
     * 
     * @param groupId 
     * @return DevicesGroupDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun groupControllerGetGroupDevices(groupId: kotlin.String) : DevicesGroupDto {
        val localVarResponse = groupControllerGetGroupDevicesWithHttpInfo(groupId = groupId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DevicesGroupDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/group/{groupId}/devices
     * Get Devices in a group
     * 
     * @param groupId 
     * @return ApiResponse<DevicesGroupDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun groupControllerGetGroupDevicesWithHttpInfo(groupId: kotlin.String) : ApiResponse<DevicesGroupDto?> {
        val localVariableConfig = groupControllerGetGroupDevicesRequestConfig(groupId = groupId)

        return request<Unit, DevicesGroupDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation groupControllerGetGroupDevices
     *
     * @param groupId 
     * @return RequestConfig
     */
    fun groupControllerGetGroupDevicesRequestConfig(groupId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/group/{groupId}/devices".replace("{"+"groupId"+"}", encodeURIComponent(groupId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/group
     * Get Devices Groups and children groups
     * 
     * @return kotlin.collections.List<DevicesGroupDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun groupControllerGetGroups() : kotlin.collections.List<DevicesGroupDto> {
        val localVarResponse = groupControllerGetGroupsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<DevicesGroupDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/group
     * Get Devices Groups and children groups
     * 
     * @return ApiResponse<kotlin.collections.List<DevicesGroupDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun groupControllerGetGroupsWithHttpInfo() : ApiResponse<kotlin.collections.List<DevicesGroupDto>?> {
        val localVariableConfig = groupControllerGetGroupsRequestConfig()

        return request<Unit, kotlin.collections.List<DevicesGroupDto>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation groupControllerGetGroups
     *
     * @return RequestConfig
     */
    fun groupControllerGetGroupsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/group",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/group/devices
     * Set Devices in a Group
     * 
     * @param setDevicesInGroupDto 
     * @return DevicesGroupDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun groupControllerSetDevicesInGroup(setDevicesInGroupDto: SetDevicesInGroupDto) : DevicesGroupDto {
        val localVarResponse = groupControllerSetDevicesInGroupWithHttpInfo(setDevicesInGroupDto = setDevicesInGroupDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DevicesGroupDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/group/devices
     * Set Devices in a Group
     * 
     * @param setDevicesInGroupDto 
     * @return ApiResponse<DevicesGroupDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun groupControllerSetDevicesInGroupWithHttpInfo(setDevicesInGroupDto: SetDevicesInGroupDto) : ApiResponse<DevicesGroupDto?> {
        val localVariableConfig = groupControllerSetDevicesInGroupRequestConfig(setDevicesInGroupDto = setDevicesInGroupDto)

        return request<SetDevicesInGroupDto, DevicesGroupDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation groupControllerSetDevicesInGroup
     *
     * @param setDevicesInGroupDto 
     * @return RequestConfig
     */
    fun groupControllerSetDevicesInGroupRequestConfig(setDevicesInGroupDto: SetDevicesInGroupDto) : RequestConfig<SetDevicesInGroupDto> {
        val localVariableBody = setDevicesInGroupDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/group/devices",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
