name: Mirroring

on:
  push:
    branches:
      - mirror
    tags:
      - 'v*.*.*'
  delete:
    branches:
      - mirror

jobs:
  to_private_repo:
    runs-on: ubuntu-latest
    if: ${{ github.repository_visibility == 'public' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:getappsh/get-map-android-sdk-private.git
          ssh_private_key:
            ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}