name: Build and Release Android App

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_visibility == 'private' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Create secrets.properties file for public env
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> ./secrets.properties
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> ./secrets.properties
          echo "AW_USER_NAME=1" >> ./secrets.properties
          echo "AW_PASSWORD=1" >> ./secrets.properties
          echo "AW_API=1" >> ./secrets.properties
          echo "AIRWATCH_TENANT=1" >> ./secrets.properties
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> ./secrets.properties
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> ./secrets.properties

      - name: Build the pub app
        run: ./gradlew :example-app:assembleDebug

      - name: Upload pub APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-pub
          path: example-app/build/outputs/apk/debug/*.apk

      - name: Create secrets.properties file for even env
        run: |
          rm ./secrets.properties
          ls
          echo "USERNAME=${{ secrets.EVEN_USERNAME }}" >> ./secrets.properties
          echo "PASSWORD=${{ secrets.EVEN_PASSWORD }}" >> ./secrets.properties
          echo "AW_USER_NAME=${{ secrets.EVEN_AW_USER_NAME }}" >> ./secrets.properties
          echo "AW_PASSWORD=${{ secrets.EVEN_AW_PASSWORD }}" >> ./secrets.properties
          echo "AW_API=${{ secrets.EVEN_AW_API }}" >> ./secrets.properties
          echo "AIRWATCH_TENANT=${{ secrets.EVEN_AIRWATCH_TENANT }}" >> ./secrets.properties
          echo "BASE_URL=${{ secrets.EVEN_BASE_URL }}" >> ./secrets.properties
          echo "ENCRYPTION_KEY=${{ secrets.EVEN_ENCRYPTION_KEY }}" >> ./secrets.properties

      - name: Build the Even app
        run: ./gradlew :example-app:assembleDebug -PdeployEnv='even'

      - name: Upload even APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-even
          path: example-app/build/outputs/apk/debug/*.apk


  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.repository_visibility == 'private' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download pub APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug-pub
          path: app-debug-pub

      - name: Download even APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug-even
          path: app-debug-even

      - name: Extract Version Name
        run: |
          VERSION_NAME=$(grep -oP 'versionName\s*=\s*"\K[^"]+' example-app/build.gradle.kts)
          FULL_VERSION_NAME="v${VERSION_NAME}-CM"
          echo "FULL_VERSION_NAME=${FULL_VERSION_NAME}" >> $GITHUB_ENV
          echo FULL_VERSION_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.FULL_VERSION_NAME }}
          name: Release ${{ env.FULL_VERSION_NAME }}
          draft: true
          prerelease: false
          files: |
            app-debug-pub/*.apk
            app-debug-even/*.apk